const cryptos = [
  { name: "bitcoin", ticker: "btc", cnt: 0 },
  { name: "ethereum", ticker: "eth", cnt: 0 },
  { name: "tether", ticker: "usdt", cnt: 0 },
  { name: "binance coin", ticker: "bnb", cnt: 0 },
  { name: "usd coin", ticker: "usdc", cnt: 0 },
  { name: "xrp", ticker: "xrp", cnt: 0 },
  { name: "binance usd", ticker: "busd", cnt: 0 },
  { name: "cardano", ticker: "ada", cnt: 0 },
  { name: "solana", ticker: "sol", cnt: 0 },
  { name: "dogecoin", ticker: "doge", cnt: 0 },
  { name: "polkadot", ticker: "dot", cnt: 0 },
  { name: "shiba inu", ticker: "shib", cnt: 0 },
  { name: "polygon", ticker: "matic", cnt: 0 },
  { name: "tron", ticker: "trx", cnt: 0 },
  { name: "litecoin", ticker: "ltc", cnt: 0 },
  { name: "dai", ticker: "dai", cnt: 0 },
  { name: "uniswap", ticker: "uni", cnt: 0 },
  { name: "wrapped bitcoin", ticker: "wbtc", cnt: 0 },
  { name: "chainlink", ticker: "link", cnt: 0 },
  { name: "avalanche", ticker: "avax", cnt: 0 },
  { name: "ethereum classic", ticker: "etc", cnt: 0 },
  { name: "stellar", ticker: "xlm", cnt: 0 },
  { name: "bitcoin cash", ticker: "bch", cnt: 0 },
  { name: "internet computer", ticker: "icp", cnt: 0 },
  { name: "algorand", ticker: "algo", cnt: 0 },
  { name: "cosmos", ticker: "atom", cnt: 0 },
  { name: "hedera", ticker: "hbar", cnt: 0 },
  { name: "filecoin", ticker: "fil", cnt: 0 },
  { name: "monero", ticker: "xmr", cnt: 0 },
  { name: "elrond", ticker: "egld", cnt: 0 },
  { name: "aave", ticker: "aave", cnt: 0 },
  { name: "tezos", ticker: "xtz", cnt: 0 },
  { name: "pancakeswap", ticker: "cake", cnt: 0 },
  { name: "iota", ticker: "iota", cnt: 0 },
  { name: "vechain", ticker: "vet", cnt: 0 },
  { name: "theta network", ticker: "theta", cnt: 0 },
  { name: "zcash", ticker: "zec", cnt: 0 },
  { name: "kusama", ticker: "ksm", cnt: 0 },
  { name: "sushiswap", ticker: "sushi", cnt: 0 },
  { name: "holo", ticker: "hot", cnt: 0 },
  { name: "quant", ticker: "qnt", cnt: 0 },
  { name: "kava", ticker: "kava", cnt: 0 },
  { name: "helium", ticker: "hnt", cnt: 0 },
  { name: "enjin coin", ticker: "enj", cnt: 0 },
  { name: "celo", ticker: "celo", cnt: 0 },
  { name: "decentraland", ticker: "mana", cnt: 0 },
  { name: "basic attention token", ticker: "bat", cnt: 0 },
  { name: "ravencoin", ticker: "rvn", cnt: 0 },
  { name: "rally", ticker: "rly", cnt: 0 },
  { name: "chiliz", ticker: "chz", cnt: 0 },
  { name: "nexo", ticker: "nexo", cnt: 0 },
  { name: "omg network", ticker: "omg", cnt: 0 },
  { name: "loopring", ticker: "lrc", cnt: 0 },
  { name: "synthetix", ticker: "snx", cnt: 0 },
  { name: "fantom", ticker: "ftm", cnt: 0 },
  { name: "curve dao token", ticker: "crv", cnt: 0 },
  { name: "yearn.finance", ticker: "yfi", cnt: 0 },
  { name: "stacks", ticker: "stx", cnt: 0 },
  { name: "zilliqa", ticker: "zil", cnt: 0 },
  { name: "horizen", ticker: "zen", cnt: 0 },
  { name: "theta fuel", ticker: "tfuel", cnt: 0 },
  { name: "swipe", ticker: "sxp", cnt: 0 },
  { name: "1inch", ticker: "1inch", cnt: 0 },
  { name: "celer network", ticker: "celr", cnt: 0 },
  { name: "hedera hashgraph", ticker: "hbar", cnt: 0 },
  { name: "nem", ticker: "xem", cnt: 0 },
  { name: "ankr", ticker: "ankr", cnt: 0 },
  { name: "firo", ticker: "firo", cnt: 0 },
  { name: "ocean protocol", ticker: "ocean", cnt: 0 },
  { name: "the graph", ticker: "grt", cnt: 0 },
  { name: "quantstamp", ticker: "qsp", cnt: 0 },
  { name: "terra", ticker: "luna", cnt: 0 },
  { name: "titanswap", ticker: "titan", cnt: 0 },
  { name: "wazirx", ticker: "wrx", cnt: 0 },
  { name: "eos", ticker: "eos", cnt: 0 },
  { name: "uphold", ticker: "upt", cnt: 0 },
  { name: "nkn", ticker: "nkn", cnt: 0 },
  { name: "storj", ticker: "storj", cnt: 0 },
  { name: "balancer", ticker: "bal", cnt: 0 },
  { name: "perpetual protocol", ticker: "perp", cnt: 0 },
  { name: "energy web token", ticker: "ewt", cnt: 0 },
  { name: "lido", ticker: "ldo", cnt: 0 },
  { name: "sora", ticker: "xor", cnt: 0 },
  { name: "ren", ticker: "ren", cnt: 0 },
  { name: "celo dollar", ticker: "cusd", cnt: 0 },
  { name: "bakeryswap", ticker: "bake", cnt: 0 },
  { name: "civic", ticker: "cvc", cnt: 0 },
  { name: "fetch.ai", ticker: "fet", cnt: 0 },
  { name: "render token", ticker: "rndr", cnt: 0 },
  { name: "cortex", ticker: "ctxc", cnt: 0 },
  { name: "rari governance token", ticker: "rgt", cnt: 0 },
  { name: "pundi x", ticker: "pundix", cnt: 0 },
  { name: "pax dollar", ticker: "usdp", cnt: 0 },
  { name: "verge", ticker: "xvg", cnt: 0 },
  { name: "dodo", ticker: "dodo", cnt: 0 },
  { name: "keep3rv1", ticker: "kp3r", cnt: 0 },
  { name: "mirror protocol", ticker: "mir", cnt: 0 },
  { name: "golem", ticker: "glm", cnt: 0 },
  { name: "ethernity chain", ticker: "ern", cnt: 0 },
  { name: "hegic", ticker: "hegic", cnt: 0 },
];

module.exports = cryptos;
